from dotenv import dotenv_values

conf = dotenv_values('.env')

BILINE_BASE_URL = conf['BILINE_BASE_URL']
BILINE_CLIENT_ID = conf['BILINE_CLIENT_ID']
BILINE_CLIENT_SECRET = conf['BILINE_CLIENT_SECRET']
BILINE_USERNAME = conf['BILINE_USERNAME']
BILINE_PASSWORD = conf['BILINE_PASSWORD']
BILINE_DASHBORD = conf['BILINE_DASHBORD']

MTS_BASE_URL = conf['MTS_BASE_URL']
MTS_USERNAME = conf['MTS_USERNAME']
MTS_PASSWORD = conf['MTS_PASSWORD']
MTS_PARENT_TEL_NUMBER = conf['MTS_PARENT_TEL_NUMBER']

TELE_TWO_BASE_URL = conf['TELE_TWO_BASE_URL']
TELE_TWO_USERNAME = conf['TELE_TWO_USERNAME']
TELE_TWO_PASSWORD = conf['TELE_TWO_PASSWORD']

